method: grid
parameters:
  model:
    value: "GNN"
  feats:
    value: "pos"
  target:
    value: ["Omega_m", "sigma_8"]
  learning_rate:
    value: 0.0001
  decay:
    value: 0.00001
  steps:
    value: 5000
  batch_size:
    value: 32
  n_radial_basis:
    values: [0, 4, 8]
  use_tpcf:
    value: 'none'
  k:
    value: 20
  radius:
    value: null
  message_passing_agg:
    values: ['sum', 'mean']
  readout_agg:
    values: ['mean']
  message_passing_steps:
    values: [2, 3, 4]
  n_layers: 
    value: 3
  d_hidden:
    value: 128
