method: grid
parameters:
  model:
    value: "MLP"
  feats:
    value: "pos"
  target:
    values: [["Omega_m", "sigma_8"], ["Omega_m"], ["sigma_8"]]
  learning_rate:
    values: [0.001]
  decay:
    value: 0.00001
  steps:
    value: 5000
  batch_size:
    values: [32]
  n_radial_basis:
    value: 0
  use_tpcf:
    value: 'all'
  k:
    value: 20
  radius:
    value: null
  d_hidden: 
    value: 128