method: grid
parameters:
  model:
    value: "NequIP"
  feats:
    value: "pos"
  target:
    value: ["Omega_m", "sigma_8"]
  learning_rate:
    value: 0.0001
  decay:
    value: 0.00001
  steps:
    value: 5000
  batch_size:
    values: [32]
  use_rbf:
    value: False
  use_tpcf:
    value: 'none'
  k:
    value: 20
  radius:
    value: null
  message_passing_agg:
    values: ['sum', 'mean']
  readout_agg:
    values: ['sum', 'mean']
  message_passing_steps:
    values: [3, 4]
  n_layers: 
    values: [3]
  d_hidden:
    values: [128]
  l_max_hidden:
    values: [1, 2]
  l_max_attr:
    values: [1, 2]
  sphharm_norm:
    values: ["integral", "component", "norm"]
  num_message_passing_steps:
    values: [2, 4]
  normalize_messages:
    values: [True, False]
  message_passing_agg:
    values: ['sum', 'mean']
  readout_agg:
    values: ['sum', 'mean']
  n_radial_basis:
    values: [4, 8]