method: grid
parameters:
  model:
    value: "SEGNN"
  feats:
    value: "pos"
  target:
    value: ["Omega_m", "sigma_8"]
  learning_rate:
    value: 0.0001
  decay:
    value: 0.00001
  steps:
    value: 5000
  batch_size:
    value: 32
  n_radial_basis:
    values: [4, 8]
  use_tpcf:
    value: 'none'
  k:
    value: 20
  radius:
    value: null
  message_passing_agg:
    values: ['sum', 'mean']
  readout_agg:
    value: 'mean'
  normalize_messages:
    values: [True, False]
  message_passing_steps:
    values: [2, 3]
  n_layers: 
    value: 3
  d_hidden:
    value: 64
  num_blocks:
    values: [3]
  residual:
    value: True
  intermediate_hidden_irreps:
    value: True
  
